Relax lifetime restriction and avoid passing owned op to `OpBuilderLike` (#307)
* avoid `for<'a>` because it prohibitively restricts the `OperationRef`
* add `OperationRefLike` trait for all non-owned op struct
* fix other cases of owned value being used for insertion point
* add direct "nix build" CI check
* update `install-nix-action` version

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,6 +7,28 @@ on:
       - main
 
 jobs:
+  build-nix:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+      - uses: cachix/install-nix-action@v31.11.0
+        with:
+          install_url: https://releases.nixos.org/nix/nix-2.31.2/install
+          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
+      - name: Set Git credentials
+        run: |
+          git config --global 'url.https://api@github.com/'.insteadOf 'https://github.com/'
+          git config --global 'url.https://ssh@github.com/'.insteadOf 'ssh://git@github.com/'
+          git config --global 'url.https://git@github.com/'.insteadOf 'git@github.com:'
+      - uses: cachix/cachix-action@v17
+        with:
+          name: veridise-public
+          authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
+      - name: Build and test
+        run: nix --print-build-logs build
+
   build:
     runs-on: ubuntu-latest
     strategy:
@@ -18,7 +40,7 @@ jobs:
       - uses: actions/checkout@v6
         with:
           persist-credentials: false
-      - uses: cachix/install-nix-action@9280e7aca88deada44c930f1e2c78e21c3ae3edd # v31.7.0
+      - uses: cachix/install-nix-action@v31.11.0
         with:
           install_url: https://releases.nixos.org/nix/nix-2.31.2/install
           github_access_token: "${{ secrets.GITHUB_TOKEN }}"
@@ -50,7 +72,7 @@ jobs:
 
   # WARNING: do not change this job name. It is a required status check for PRs to `main`.
   build-result:
-    needs: build
+    needs: [build, build-nix]
     runs-on: ubuntu-latest
     if: ${{ !cancelled() }}
     steps:
@@ -58,6 +80,10 @@ jobs:
         run: |
           if [[ "${{ needs.build.result }}" != "success" ]]; then
             echo "build failed or was cancelled"
+            exit 1
+          fi
+          if [[ "${{ needs.build-nix.result }}" != "success" ]]; then
+            echo "build-nix failed or was cancelled"
             exit 1
           fi
 
@@ -68,7 +94,7 @@ jobs:
       - uses: actions/checkout@v6
         with:
           persist-credentials: false
-      - uses: cachix/install-nix-action@9280e7aca88deada44c930f1e2c78e21c3ae3edd # v31.7.0
+      - uses: cachix/install-nix-action@v31.11.0
         with:
           install_url: https://releases.nixos.org/nix/nix-2.31.2/install
           github_access_token: "${{ secrets.GITHUB_TOKEN }}"
@@ -121,7 +147,7 @@ jobs:
       - uses: actions/checkout@v6
         with:
           persist-credentials: false
-      - uses: cachix/install-nix-action@9280e7aca88deada44c930f1e2c78e21c3ae3edd # v31.7.0
+      - uses: cachix/install-nix-action@v31.11.0
         with:
           install_url: https://releases.nixos.org/nix/nix-2.31.2/install
           github_access_token: "${{ secrets.GITHUB_TOKEN }}"
